a = input ('Digite algo: ')
print ('O tipo primitivo desse valor é ', type(a))
print ('Só tem espaços?', a.isspace())
print ('É um numero ', a.isnumeric())
print ('É alfabetico ', a.isalnum())
print ('É alfanumerico ?' , a.isalpha())
print ('Está em maiúsculas ? ', a.isupper())
print ('Esta em minúsculas ? ', a.islower())
print ('Está capitalizada ? ', a.istitle())